nodeLinker: node-modules
npmMinimalAgeGate: "3d"
# stupid hack for recharts which has a peer dependency on react-is but doesn't declare it as a dependency
# https://github.com/recharts/recharts/issues/7186
packageExtensions:
  "recharts@*":
    dependencies:
      react-is: "*"
