export interface Me {
	seller: {
		_id: string;
		name: string;
		currency: string;
		locationName: string;
		locationStreet: string;
		locationCity: string;
		locationPostal: string;
		locationCountry: string;
		outerChargeVar: number;
		innerChargeVar: number;
		outerChargeFix: number;
		innerChargeFix: number;
		groupInnerChargeFix: number;
		freeTicketInnerChargeFix: number;
		cartOuterChargeFix: number;
		cartInnerChargeFix: number;
		freeCartOuterChargeFix: number;
		freeCartInnerChargeFix: number;
		posChargeVar: number;
		posChargeFix: number;
		freeTicketPOSChargeFix: number;
		posOuterChargeVar: number;
		posOuterChargeFix: number;
		paymentChargeVar: number;
		rebookingOuterChargeFix: number;
		additionalFees: {
			chargebackFee: number;
			cancellationFee: number;
			eventCancellationFee: number;
			fiscalizationFee: number;
			chargeFiscalizationFee: boolean;
			_id: string;
		};
		active: boolean;
		accentColor: string;
		payment: {
			managedPayments: boolean;
			vivenuPayments: boolean;
			methods: {
				paypal: boolean;
				klarna: boolean;
				ideal: boolean;
				sepa: boolean;
				creditcard: boolean;
				mobilepay: boolean;
				blik: boolean;
				p24: boolean;
				affirm: boolean;
				bancontact: boolean;
				afterpay: boolean;
				zip: boolean;
				ach: boolean;
				_id: string;
			};
			additionalMethods: any[];
			_id: string;
		};
		taxSetting: {
			taxRate: number;
			taxId: string;
			localTaxName: string;
			createInvoiceAfterTransaction: boolean;
			sendTaxInvoiceToCustomer: boolean;
			serviceTypes: any[];
			taxTypes: { _id: string; name: string }[];
			accounts: any[];
			regions: any[];
			taxCalculationMethod: string;
			_id: string;
		};
		customFieldsConfig: {
			customers: any[];
		};
		shopSettings: any;
		documentSettings: any;
		deliverySettings: any;
		modules: any;
		localeSettings: any;
		ticketSettings: any;
		customerSettings: any;
		supportSettings: any;
		posSettings: any;
		orgId: string;
		status: string;
		legalSettings: any;
		priceCategories: any[];
		accessControlEntries: any[];
		brandingSettings: any;
		feeSettings: any;
		fulfillmentTypes: any[];
		createdAt: string;
		updatedAt: string;
		__v: number;
		url: string;
		accessControlSettings: any;
		customTextConfig: any;
		dataRequestSettings: any;
		mailingSettings: any;
		consents: any;
		image: string;
		agb: string;
		imprint: string;
		website: string;
		privacy: string;
		supportUrl: string;
		description: string;
		contractTypes: any[];
		organization: {
			_id: string;
			name: string;
		};
	};
	me: {
		_id: string;
		email: string;
		name: string;
		isAdmin: boolean;
		isSuperAdmin: boolean;
		loginType: string;
		sellerAccess: string;
		sellers: string[];
		granularPermissionsForSellers: string[];
		permissions: { type: string; scope: string }[];
		roles: { type: string; scope: string }[];
		createdAt: string;
		updatedAt: string;
		__v: number;
		lastLogin: string;
		twoFactorAuthSettings: {
			defaultMethod: string;
			totp: {
				verifiedAt: string;
			};
		};
	};
	orgAccessableSellerIds: string[];
}
